GET http://localhost:4000/api/toilets 


###
GET http://localhost:4000/api/toilets/60a757303e80510d88a709d3

###

POST http://localhost:4000/api/toilets
Content-Type: application/json

{
    "location": "Hive",
    "lat" : 1.3431297652528165, 
    "lng" : 103.68278744519097,
    "hasBidet": true,
    "name": "Hive basement toilet",
    "rating": 6
}

###

DELETE http://localhost:4000/api/toilets/60a4ac578d41a30624ae4e57  

###

PATCH http://localhost:4000/api/toilets/60a50a276d5a4e4224e726b8
Content-Type: application/json

{
    "image_url" : "https://i1.wp.com/u-insight.com/wp-content/uploads/2020/01/food6.png?resize=860%2C644&ssl=1"
}