GET http://localhost:4000/api/toilets 


###
GET http://localhost:4000/api/toilets/60a69ad2016b594ea8d3e479

###

GET http://localhost:4000/api/reviews/60b5029651b593575c57c4bc

###

POST http://localhost:4000/api/toilets
Content-Type: application/json

{
    "location": "Hive",
    "lat" : 1.3431297652528165, 
    "lng" : 103.68278744519097,
    "hasBidet": false,
    "name": "Hive basement toilet",
    "rating": 10
}

###

POST http://localhost:4000/api/reviews
Content-Type: application/json

{
    "reviewText": "Nice",
    "toiletID": "60a69ad2016b594ea8d3e479",
    "date": "2021-5-31",
    "rating" : 4
}

###

DELETE http://localhost:4000/api/toilets/60d031216355124d207502ca

###


DELETE http://localhost:4000/api/reviews/60d031216355124d207502ca


###

PATCH http://localhost:4000/api/toilets/60a69ad2016b594ea8d3e479
Content-Type: application/json

{
    "image_url" : "https://media.timeout.com/images/105290175/630/472/image.jpg"
}



###
POST http://localhost:4000/api/replies
Content-Type: application/json

{

    "replyText": "lalalala",
    "reviewID": "60be73efdd51fd7195fb13f9",
    "date" : "2021-05-23"
}



###

GET http://localhost:4000/api/reviews/replies/toilet?toiletID=60c0fefb0753e03f9c922c7d



###
GET https://ntu-toilet-app.herokuapp.com/reviews