GET http://localhost:4000/api/toilets 


###
GET http://localhost:4000/api/toilets/60a757303e80510d88a709d3

###

GET http://localhost:4000/api/reviews/60b5029651b593575c57c4bc

###

POST http://localhost:4000/api/toilets
Content-Type: application/json

{
    "location": "Hive",
    "lat" : 1.3431297652528165, 
    "lng" : 103.68278744519097,
    "hasBidet": false,
    "name": "Hive basement toilet",
    "rating": 10
}

###

POST http://localhost:4000/api/reviews
Content-Type: application/json

{
    "reviewText": "Nice",
    "toiletID": "60a757303e80510d88a709d3",
    "date": "2021-5-31"
}

###

DELETE http://localhost:4000/api/toilets/60a69edb016b594ea8d3e47a

###


DELETE http://localhost:4000/api/reviews/60b5029651b593575c57c4bc


###

PATCH http://localhost:4000/toilets/60a757303e80510d88a709d3
Content-Type: application/json

{
    "image_url" : "https://media.timeout.com/images/105290175/630/472/image.jpg"
}